<?php
        $apiKey="rzp_test_yyyhrBTevF6kJH";
        include 'config.php';
        session_start();
        $session=$_SESSION['user'];
        $sqlii="SELECT tbl_users.login_id,tbl_users.name,tbl_users.phone,tbl_users.address,tbl_users.userid,tbl_orders.booking_id,tbl_orders.amount,tbl_orders.transaction from tbl_orders join tbl_users on tbl_users.login_id=tbl_orders.login_id where tbl_users.login_id='$session'";
        $result = mysqli_query($con, $sqlii);
        while ($row = mysqli_fetch_assoc($result)) {
            $id= $row['booking_id'];
            $amount=$row['amount'];
            $name=$row['name'];

        }
        $sql=mysqli_query($con,"SELECT SUM(amount) from tbl_orders where login_id='$session' and transaction='pending' ");
        while($er=mysqli_fetch_array($sql)){
            $amounts=$er['SUM(amount)'];
        
        }
?>
<form action="payment_action.php?bid=<?php echo $id ?>&&id=<?php echo $amounts ?>" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amounts * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="Dust 2 Shine"
    data-description="Add more colors to your day"
    data-image=""
    data-prefill.name="<?php echo $name;?>"
    data-prefill.email=""
    data-theme.color="#4e39e5"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form> 

<style>
.razorpay-payment-button { 
        margin-left:750px;
        margin-top: 400px;
        display: inline-block;
        background-color: #4e39e5;
        border-radius: 10px;
        border: 4px double #cccccc;
        color: #eeeeee;
        text-align: center;
        font-size: 28px;
        padding: 20px;
        width: 200px;
        -webkit-transition: all 0.5s;
        -moz-transition: all 0.5s;
        -o-transition: all 0.5s;
        transition: all 0.5s;
        cursor: pointer;
        -webkit-transition-duration: 0.8s; /* Safari */
        transition-duration: 0.4s;
         box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        /*margin: 5px;*/
 }
</style>


<!-- <script type="text/javascript">
  $(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script--> 